import type { Metadata } from "next";
import "./globals.css";
// import NavBar from "./components/NavBar";
import { geistSans } from "./fonts";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} salt content-box antialiased pt-24 `}
      >
          <div className="flex items-center p-4 w-full h-[5.25rem] fixed z-50 bottom-0 left-0 bg-white border-none">
            <div className=" flex items-center justify-center text-white  bg-red-600 w-full h-full rounded-md font-semibold">Offer Trade</div>
          </div>
        {children}
      </body>
    </html>
  );
}
